name: Test and Deploy to Google Cloud Run

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Test and Deploy to Google Cloud Run
        runs-on: ubuntu-latest

        env:
            GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
            GCP_REGION: ${{ vars.GCP_REGION }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install pnpm
              run: |
                  npm install -g pnpm

            - name: Install dependencies
              run: |
                  pnpm install

            - name: Run lint:fix
              run: |
                  pnpm lint:fix

            - name: Run format:fix
              run: |
                  pnpm format:fix

            - name: Run tests
              env:
                  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
              run: |
                  pnpm test

            - name: Run E2E tests
              run: |
                  pnpm test:e2e

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v1
              with:
                  project_id: ${{ env.GCP_PROJECT_ID }}

            - name: Configure Docker for Artifact Registry
              run: |
                  gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

            - name: Build and push Docker image
              run: |
                  docker build -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/cloud-run-source-deploy/${{ env.GCP_PROJECT_ID }}:$GITHUB_SHA .
                  docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/cloud-run-source-deploy/${{ env.GCP_PROJECT_ID }}:$GITHUB_SHA

            - name: Deploy to Cloud Run
              run: |
                  gcloud run deploy ${{ env.GCP_PROJECT_ID }} \
                    --image ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/cloud-run-source-deploy/${{ env.GCP_PROJECT_ID }}:$GITHUB_SHA \
                    --platform managed \
                    --region ${{ env.GCP_REGION }} \
                    --service-account ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }} \
                    --no-allow-unauthenticated
